FROM php:5.6

MAINTAINER Emiliano G. Molina <emiliano.g.molina@gmail.com>

# Install system packages
RUN apt-get update && apt-get install -y \
    curl \
    git \
    wget

# Install PHP composer 
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Create application workspace
RUN mkdir -p /var/www
WORKDIR /var/www

# Deploy application
COPY . /var/www

# Create mount point
VOLUME /var/www

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["echo"]
